### ISSUE TITLE
remove IDO dependency

### ISSUE THREAD

**Issue by cmungall** [EcologicalSemantics/ecocore#102]
It is injecting bad axioms to uberon causing unsatisfiability

For now, when making ontologies like ECOCORE we need to be very careful with each import, ask if we really need it, evaluate it for injection attacks, and be defensive in use.

Currently there is one IDO class directly referenced from ecocore, endosymbiont. I do not think it is out of place to suggest that this should not be in IDO because there are many non-disease endosymbiont. We need to think more about modularity across OBO!

**Comment by diatomsRcool** [comment]
done in latest release
