### ISSUE TITLE
NTR: active foraging

### ISSUE THREAD

**Issue by diatomsRcool** [EcologicalSemantics/ecocore#111]
For new term requests, please provide the following information:

## Preferred term label

active foraging

## Textual definition

heterotrophic process during which a living entity acquires food and energy by actively searching for food resources that put up little to no resistance to being consumed

## Suggested parent term

heterotrophy

## Attribution

http://orcid.org/0000-0002-2908-3327

**Comment by diatomsRcool** [comment]
See https://github.com/EcologicalSemantics/ecocore/issues/93 for context

**Comment by diatomsRcool** [comment]
@jhammock @KatjaSchulz thoughts?

**Comment by jhammock** [comment]
I don't see the use of excluding motile prey, but here's the thought experiment: if active foraging is a sister to hunting, what is their parent?

**Comment by KatjaSchulz** [comment]
I would think active foraging would be a parent to hunting.

**Comment by diatomsRcool** [comment]
you know what. This belongs in the behavior ontology

**Comment by diatomsRcool** [comment]
I'm closing this because its been added to NBO.
