### ISSUE TITLE
creation of a class for species range needed in the biorealm ontology

### ISSUE THREAD

**Issue by thearyung** [EcologicalSemantics/ecocore#117]
in our new [biorealm ontology](https://github.com/EnvironmentOntology/biorealm) we would like to express the areas where a population of taxa live and interact with its ecosystem.
We propose the following: 
 **label**: population range

**definition**: an ecosystem which is delimited by the ranges of an ecological population

**Comment by diatomsRcool** [comment]
@ramonawalls should this term go in PCO instead?

**Comment by ramonawalls** [comment]
I do think PCO is a reasonable place for population range. I think @thearyung should be able to transfer this issue to https://github.com/PopulationAndCommunityOntology/pco/issues.

**Comment by thearyung** [comment]
Thnaks, I'll create a new issue in PCO

**Comment by diatomsRcool** [comment]
I'm going to go ahead and close this issue. If that is premature, feel free to reopen.

**Comment by ramonawalls** [comment]
Moving this request back here and about to create a PR.
