### ISSUE TITLE
'causally related to' sub: 'causal relation between material entity and a process' not in RO

### ISSUE THREAD

**Issue by matentzn** [EcologicalSemantics/ecocore#121]
Hey! The axiom `'causally related to' sub: 'causal relation between material entity and a process'` is not in RO, but is still in ecocore and causing some issues. Is there a way that for the next release, we can get rid of that?

**Comment by matentzn** [comment]
https://github.com/INCATools/ontology-development-kit/issues/345

**Comment by matentzn** [comment]
That fixed it it seems! The problematic axiom does not seem to be there anymore!

**Comment by diatomsRcool** [comment]
I'm still getting an unsatisfiable class. What are you looking at that shows the problem is solved?
