### ISSUE TITLE
NTRs: {symbiotic,commensal,parasitic} interaction process

### ISSUE THREAD

**Issue by cmungall** [EcologicalSemantics/ecocore#124]
GO is no longer the home of these concepts. GO is for representing the evolved biollogica program that are executed in the organism allowing for the interaction

https://github.com/geneontology/go-ontology/issues/20191

ecocore seems like the best home - will you take them?

to be clear, these would be new IDs in ECOCORE. IMO GO should have obsoleted its IDs but anyway they are remaining despite change in def.

**Comment by diatomsRcool** [comment]
For clarity: would Symbiotrophy (ecocore:00000060) work for 'symbiotic interaction process'? The definition is 'A heterotrophic process during which a living entity acquires food and energy through a symbiotic relationship with another organism.' If so, I can create classes for the other processes following this model.

**Comment by diatomsRcool** [comment]
Fixed in v2022-03-09
