### ISSUE TITLE
The PURL for ECOCORE_00000103 and ECOCORE_00000037 are wrong

### ISSUE THREAD

**Issue by matentzn** [EcologicalSemantics/ecocore#130]
https://www.ebi.ac.uk/ols/ontologies/ecocore/terms?iri=http%3A%2F%2Fobolibrary.org%2Fobo%2FECOCORE_00000103

http://obolibrary.org/obo/ECOCORE_00000103

should be:

http://purl.obolibrary.org/obo/ECOCORE_00000103

see:
https://github.com/orgs/OBOFoundry/projects/5

**Comment by matentzn** [comment]
same with: 

http://purl.obolibrary/obo/ECOCORE_00000037

**Comment by diatomsRcool** [comment]
Fixed in 2020-12-18 release
