### ISSUE TITLE
Ensure ecocore is complete for mixs value mapping

### ISSUE THREAD

**Issue by cmungall** [EcologicalSemantics/ecocore#131]
We have a number of fields in MIxS that have enums that should be mapped to an OBO, I think many should be in ecocore

https://github.com/microbiomedata/nmdc-metadata/blob/d27b4f6784af5f4508833e6562f316c25fb37a81/schema/mixs.yaml#L400-L412

`[aerobe|anaerobe|facultative|microaerophilic|microanaerobe|obligate aerobe|obligate anaerobe]`

https://github.com/microbiomedata/nmdc-metadata/blob/d27b4f6784af5f4508833e6562f316c25fb37a81/schema/mixs.yaml#L360-L372

`[autotroph|carboxydotroph|chemoautotroph|chemoheterotroph|chemolithoautotroph|chemolithotroph|chemoorganoheterotroph|chemoorganotroph|chemosynthetic|chemotroph|copiotroph|diazotroph|facultative|autotroph|heterotroph|lithoautotroph|lithoheterotroph|lithotroph|methanotroph|methylotroph|mixotroph|obligate|chemoautolithotroph|oligotroph|organoheterotroph|organotroph|photoautotroph|photoheterotroph|photolithoautotroph|photolithotroph|photosynthetic|phototroph]`

Ideally for each of these terms there would be a clear mapping, and we would not have to make a decision between autotrophic organism vs disposition vs process 

Some of these are in the MIXSCV ontology, but this is not up to date with the latest mixs:

https://bioportal.bioontology.org/ontologies/MIXSCV/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMVC_0000010

Related ticket: https://github.com/Knowledge-Graph-Hub/kg-microbe/issues/3

cc @wdduncan @kaiam @realmarcin @ramonawalls

**Comment by diatomsRcool** [comment]
on it - do we have term definitions that we want to use or carry over or should I start investigating?

**Comment by ramonawalls** [comment]
There are no official MIxS definitions -- it is just a CV. Great to have these terms in ecocore.

**Comment by wdduncan** [comment]
I'm doing some spot checking (on Ontobee), and I'm finding many terms in both BTO (http://purl.obolibrary.org/obo/bto.owl) and ECOCORE, and others (e.g, phototroph) in NCBITaxon.

@diatomsRcool Do you need me to help find ontology terms?

**Comment by diatomsRcool** [comment]
If you want to start digging around @wdduncan I would appreciate it

**Comment by diatomsRcool** [comment]
Added oxygen metabolism terms to ecocore-edit

**Comment by diatomsRcool** [comment]
microanaerobe: is this a synonym of microaerophile?
carboxydotroph: an organism capable of tolerating a high concentration of carbon monoxide
copiotroph: an organism capable of thriving in environments rich in nutrients, particularly carbon.
diazotroph: an organism capable of fixing atmospheric nitrogen gas into a more usable form such as ammonia
methanotroph: an organism capable of metabolizing methane as their source of carbon and energy
methylotroph: an organism capable of using one-carbon compounds and multi-carbon compounds that contain no carbon-carbon bonds as the carbon source for their growth
oligotroph: an organism capable of living in an environment that offers very low levels of nutrients

**Comment by cmungall** [comment]
@wdduncan - I don't see phototroph in NCBItaxon? I would be surprised if it was as I doubt it's a monophyletic trait

@ramonawalls - should the mixs enum really have values like `facultative`? Is this intended to be composable? E.g. such that someone could say facultative + methanotroph? Or is this implicitly facultative anaerobe?

**Comment by wdduncan** [comment]
@diatomsRcool  Are we using `metabolic process` as a synonym for `growth process`? I only ask b/c the definition for `anaerobe` uses `growth process`.

@cmungall do we want to use `has characteristic` relation for which ever approach we decide?

FWIIW, I think the process view makes more sense me. But I'm not a biologist, and thus often wrong about such things :)

**Comment by diatomsRcool** [comment]
There is a case for extending PATO. Funny, I wonder when those terms were added. I could have swore I looked for them and couldn't find them.

**Comment by wdduncan** [comment]
@diatomsRcool I didn't think they were synonyms either, but I was wanting make sure. 

As for metabolism vs growth, I don't know which is more appropriate. Do the metabolic processes for anaerobes also not require oxygen? For what I read on [Wikipedia](https://en.wikipedia.org/wiki/Anaerobic_organism) oxygen is disruptive (or harmful) to metabolic processes. Do we need to capture this too?

Also, how formal do we want the definition for anaerobic organism to be? I discussed this in this [issue](https://github.com/Knowledge-Graph-Hub/kg-microbe/issues/4) on kg-microbe.

In brief, taking the process view of `growth`, we could create an `anaerobic growth process` class like so:
```
biological process
  - growth
     - anaerobic growth process
 ```
and formally define `anaerobic growth process` as equivalent to:
```
growth process and not (has input some oxygen)
```

I'm a little wary about using the expression `not (has input some oxygen)`.

Also, is this level of formalizm useful?

**Comment by diatomsRcool** [comment]
new terms are in the 2021-02-17 release
