### ISSUE TITLE
New synonyms request : "-phage" as synonyms of "-vore"

### ISSUE THREAD

**Issue by nleguillarme** [EcologicalSemantics/ecocore#143]
Hi, I am leading a group of soil ecologists working on an ontology of soil trophic webs that reuse a lot of classes from ECOCORE, and the following synonyms were proposed during the first iteration of our ontology development process :

- [x] "fungal feeder" as exact synonym of "fungivore"
- [x] "bacterial feeder" as exact synonym of "bacterivore"
- [x] "entomophage" as exact synonym of "insectivore"
- [x] "hematophage" as exact synonym of "sanguivore"
- [x] "algophage" as exact synonym of "algivore"
- [x] "carpophage" and "fructivore" as exact synonym of "fugivore"
- [x] "phyllophage" as exact synonym of "folivore"
- [x] "rhizophage", "racidivore" and "root feeder" as exact synonym of "rhizovore"
- [x] "phytophage" as exact synonym of "herbivore"
- [x] "granivory" as exact synonym of "seed predation"
- [x] "necrophage" as exact synonym of "scavenger"

But also :
- [x] "phytophagy" as exact synonym of "herbivory"
- [x] "zoophagy" as exact synonym of "carnivory"
and so on ...

**Comment by diatomsRcool** [comment]
in ecocore-edit

**Comment by diatomsRcool** [comment]
Fixed in v2022-03-09
