### ISSUE TITLE
Mirror all trophic group with the corresponding trophic process

### ISSUE THREAD

**Issue by nleguillarme** [EcologicalSemantics/ecocore#149]
For instance, there is no concept "photoheterotrophy" corresponding to "photoheterotroph" organisms, and so on...

**Comment by diatomsRcool** [comment]
I have been working on this. There are a few different ways to do it. I am not sure that a full "mirror" is the best way to do this. I need to understand your use case better. Can you describe why you need a process class for every organism class?

**Comment by diatomsRcool** [comment]
I *think* I've fixed this in a way that will work for you.
Fixed in v2022-03-09
Reopen if not true.
