### ISSUE TITLE
Wrong superclasses for chemolithoautotroph

### ISSUE THREAD

**Issue by nleguillarme** [EcologicalSemantics/ecocore#150]
It seems weird to me that chemolithoautotroph is a subclass of chemolithoheterotroph and chemoorganoautotroph

I think it is due to the fact that the equivalence axioms for chemoorganoautotroph and chemolithoheterotroph are too permissive :
- chemoorganoautotroph subClassOf : capable of some chemosynthesis
- chemolithoheterotroph equivalentClass : capable of some lithotrophy
- chemolithoautotroph equivalentClass : capable of some ( lithotrophy and chemosynthesis)

http://www.ontobee.org/ontology/ECOCORE?iri=http://purl.obolibrary.org/obo/ECOCORE_00000124

**Comment by jhammock** [comment]
+1

**Comment by diatomsRcool** [comment]
Fixed in v2022-03-09
