### ISSUE TITLE
Map to LTER

### ISSUE THREAD

**Issue by pbuttigieg** [EcologicalSemantics/ecocore#19]
Xreffing part of a legacy PCO issue that ECOCORE (with support from ENVO and PCO) has a fair chance of handling...
https://github.com/PopulationAndCommunityOntology/pco/issues/15#issuecomment-111908670

```
 / LTER:655 ! processes
  is_a LTER:656 ! biological processes 
   is_a LTER:155 ! disease
   is_a LTER:186 ! evolution
    is_a LTER:14 ! adaptation
    is_a LTER:188 ! extinction
    is_a LTER:357 ! mutation
    is_a LTER:360 ! natural selection
    is_a LTER:540 ! speciation
   is_a LTER:298 ! life history
    is_a LTER:113 ! colonization
    is_a LTER:156 ! dispersal
     is_a LTER:495 ! seed dispersal
    is_a LTER:226 ! germination
    is_a LTER:236 ! growth
     is_a LTER:428 ! plant growth
     is_a LTER:597 ! tree growth
    is_a LTER:237 ! habitat selection
    is_a LTER:264 ! incubation
    is_a LTER:353 ! mortality
     is_a LTER:598 ! tree mortality
    is_a LTER:461 ! regeneration
    is_a LTER:465 ! reproduction
    is_a LTER:572 ! survival
   is_a LTER:305 ! litterfall
   is_a LTER:338 ! microbial activity
   is_a LTER:449 ! production
    is_a LTER:417 ! photosynthesis
    is_a LTER:428 ! plant growth
    is_a LTER:447 ! primary production
     is_a LTER:363 ! net primary production
      is_a LTER:36 ! annual net primary production
    is_a LTER:5 ! aboveground production
    is_a LTER:53 ! bacterial production
   is_a LTER:544 ! species interactions
    is_a LTER:120 ! competition
    is_a LTER:233 ! grazing
    is_a LTER:244 ! herbivory
    is_a LTER:401 ! parasitism
    is_a LTER:444 ! predation
    is_a LTER:575 ! symbiosis
    is_a LTER:74 ! browsing
   is_a LTER:686 ! succession
   is_a LTER:689 ! translocation
   is_a LTER:88 ! carbon cycling
    is_a LTER:467 ! respiration
    is_a LTER:87 ! carbon assimilation

```

**Comment by cmungall** [comment]
ontobio 0.2.16 now has support for skos, so you can redo-alignments any time. e.g to download the skos for lter and align it to the public pco on ontobee:

```
wget <URL> -O lter.ttl
ontobio-lexmap.py skos:lter.ttl pco > mappings.tsv
```

**Comment by diatomsRcool** [comment]
@ramonawalls How do you want to divide these terms between PCO and ecocore?

**Comment by ramonawalls** [comment]
Sorry to be so slow on this. Looking at this list, I think most of these terms actually belong in GO, as biological processes. Some already exists. That said, they could be curated by EcoCore and PCO.

Does a mapping for these already exist? We could start with that and see what is left over.

In a general answer to your question, Anne, I think any terms that are specifically about processes in which populations and community participate could be managed by PCO, where as processes that are interactions could go into EcoCore. I realize that leaves a lot of gray area, but I would tend to err toward putting these kinds of things in EcoCore.

**Comment by diatomsRcool** [comment]
I can spend some time on this now. What's the best way to add these LTER references? hasDbXref?

**Comment by pbuttigieg** [comment]
Yes, this is what we use in ENVO. Include a link when possible.

**Comment by diatomsRcool** [comment]
@ramonawalls I think the following is better left in PCO
evolution
adaptation
extinction
natural selection
speciation

**Comment by diatomsRcool** [comment]
- [ ] mutation = GENO:0000492: import class
- [ ] life history = ECOCORE:00000018 - add xRef
- [ ] colonization needs new class
- [ ]  dispersal see #17 
- [ ] seed dispersal = OMIT:0027297 - not sure
- [ ] germination = OMIT:0018715 - not sure
- [ ] growth = GO:0040007 - add xref

**Comment by diatomsRcool** [comment]
LTER stuff is in skos. I don't see any text definitions.

**Comment by cmungall** [comment]
```
id: GO:0015977
name: carbon fixation
namespace: biological_process
def: "A metabolic process in which carbon (usually derived from carbon dioxide) is incorporated into organic compounds (usually carbohydrates)." [GOC:jl, GOC:mah]
synonym: "autotrophic CO2 fixation" EXACT []
synonym: "autotrophic CO2 fixation pathway" EXACT []
synonym: "autotrophy" EXACT []
synonym: "carbon dioxide fixation" NARROW []
xref: Wikipedia:Carbon_fixation
is_a: GO:0008152 ! metabolic process
is_a: GO:0071704 ! organic substance metabolic process
```

This is an argument for representing mereological sums of processes under the process branch on ENVO. Or it may be better to represent environment-level qualities for these.

OMIT: we shouldn't use this for anything outside the scope of miRNA targeting

Is there a document that describes the overall modularization strategy between PCO, ECOCORE and ENVO? Not sure I understand the principles

**Comment by diatomsRcool** [comment]
As far as carbon fixation goes, I would call it a process. I'll have to discuss with Pier about whether to put it in EnVO or ecocore. Carbon fixation is a process that is measured and represented in a variety of ways, often something like "net annual primary production". This is what I would call a quality of an environment.
I will NOT use OMIT.
Right now there is no document. I should put that in the readme.

**Comment by diatomsRcool** [comment]
production in LTER is a subclass of process, so I think they are referring to carbon fixation. I will need to add that from GO.

**Comment by diatomsRcool** [comment]
John Porter at Univ VA is the contact for LTER term definitions. 
jhp7e@virginia.edu

**Comment by diatomsRcool** [comment]
Was just informed that the LTER will be undergoing some major updates in the next 6 months. We should wait on this.

**Comment by diatomsRcool** [comment]
I'm going to close this issue for now.
