### ISSUE TITLE
New Terms for EOL TraitBank - territory

### ISSUE THREAD

**Issue by diatomsRcool** [EcologicalSemantics/ecocore#29]
For new term requests, please provide the following information:

## Preferred term label

territory

## Textual definition

the sociographical area that an animal of a particular species consistently defends against conspecifics (or, occasionally, animals of other species).

## Suggested parent term

I'm not sure if this is a material or immaterial entity

## Attribution

http://orcid.org/0000-0002-2908-3327

**Comment by diatomsRcool** [comment]
I'm going to make "territory" a child of environmental zone. How does that sound @pbuttigieg ?

**Comment by pbuttigieg** [comment]
> I'm going to make "territory" a child of environmental zone. How does that sound @pbuttigieg ?

That sounds right. You could also go for BFO:site, but env. zone will probably make more sense in the long term.

> the sociographical area that an animal of a particular species consistently defends against conspecifics (or, occasionally, animals of other species).

I'm not sold on the sociographical descriptor. The definition should be more OBO compliant:
"An environmental zone which an animal consistently defends against conspecifics or, occasionally, animals of other species"

(all animals are of a particular species, so we can drop that bit)

Is there any cross-axiomatisation to a behaviour ontology or an ECOCORE extension thereof? Territorialism?

**Comment by diatomsRcool** [comment]
territory has been added.
I found territorial aggressive behavior in NBO. Not sure what kind of relation would apply here.

**Comment by diatomsRcool** [comment]
In v2019-03-15
