### ISSUE TITLE
New Term for EOL - gender arrangements

### ISSUE THREAD

**Issue by diatomsRcool** [EcologicalSemantics/ecocore#36]
For new term requests, please provide the following information:

## Preferred term label

- [x] hermaphroditic
- [x] protogynous
- [ ] diandrous - this might be a population quality ⚠️ 
- [ ] monandrous - this might be a population quality ⚠️ 

## Textual definition

a reproductive quality inhering in a bearer by virtue of the bearer having reproductive organs normally associated with both male and female sexes

a reproductive quality inhering in a bearer by virtue of the bearer having female reproductive organs at the beginning of its life and then switching to male reproductive organs

Protogynous species with both juvenile females and (primary) males, where a certain percentage of females changes into (terminal) males are termed diandric, also: possessing two different types of males, a large, brightly-coloured and aggressive terminal phase (TP) and a smaller, drab and relatively non-aggressive initial phase

Protogynous hermaphrodites with only juvenile females, where a certain percentage of females changes into (terminal) males are termed monandric.

## Suggested parent term

reproductive quality PATO:0001434

## Attribution

http://orcid.org/0000-0002-2908-3327

**Comment by diatomsRcool** [comment]
I'm not convinced those definitions of diandrous and monandrous are correct.

**Comment by diatomsRcool** [comment]
I'm not convinced diandrous and monandrous are terms for animals. I can only find plant definitions.

**Comment by pbuttigieg** [comment]
I think you're right about those being population qualities too.

**Comment by ramonawalls** [comment]
I agree that these are qualities that inhere in a population, but I think the terms should have PATO IDs.

**Comment by diatomsRcool** [comment]
diandrous: having two stamens
monandrous: with a single stamen
digynous: having two pistils

**Comment by diatomsRcool** [comment]
https://github.com/pato-ontology/pato/issues/257

**Comment by ramonawalls** [comment]
Fixed with PATO PR https://github.com/pato-ontology/pato/pull/350

**Comment by diatomsRcool** [comment]
Still waiting on a PATO PR to merge, but I'm going to close this in the meantime.
