### ISSUE TITLE
new term viral predation

### ISSUE THREAD

**Issue by diatomsRcool** [EcologicalSemantics/ecocore#45]
For new term requests, please provide the following information:

## Preferred term label

Viral predation

## Textual definition
A reproductive process wherein a virus uses another cell for reproduction. This process causes the mortality of the host cell via lysis.

## Suggested parent term

Union of lytic infection and reproduction
reproductive process

## Attribution
http://orcid.org/0000-0002-2908-3327

**Comment by diatomsRcool** [comment]
I would like to make this a child of reproductive process. I would need to import "lytic infection"

**Comment by diatomsRcool** [comment]
@pbuttigieg thoughts on the definition?

**Comment by diatomsRcool** [comment]
@pbuttigieg I just looked up lytic infection and its in NCIT. Is that still a good idea?

**Comment by diatomsRcool** [comment]
Term added in ecocore-edit as child of reproductive process

**Comment by cmungall** [comment]
shouldn't these be in GO?

**Comment by diatomsRcool** [comment]
@cmungall I dunno....should they?

**Comment by cmungall** [comment]
If it's a biological process (according to GO's definition, where the
process is achieving some evolved objective on the side of one of the
organisms)

**Comment by diatomsRcool** [comment]
@cmungall I started issue in GO.
https://github.com/geneontology/go-ontology/issues/17740

**Comment by diatomsRcool** [comment]
#119
