### ISSUE TITLE
New term Lithoautotroph

### ISSUE THREAD

**Issue by diatomsRcool** [EcologicalSemantics/ecocore#53]
For new term requests, please provide the following information:

## Preferred term label

Chemoautotroph

## Textual definition

An autotroph which is capable of acquiring energy through inorganic oxidation.

## Suggested parent term

Autotroph

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by pbuttigieg** [comment]
As with #54, we have to be careful with the synonyms and preferred labels. Going by the label, this class could also include [photolithoautotrophs](https://en.wiktionary.org/wiki/photolithoautotroph). It is thus a superclass for both photolithoautotrophs and chemolithoautotrophs.

Further, chemoautotroph as a synonym could lead to issues; however, no chemoautoorganotrophs come to mind (both reducing equivalents and C usually would come from the biogenic compound).

**Comment by diatomsRcool** [comment]
This is rolling into #55
