### ISSUE TITLE
discussion needed on primary nutritional modes

### ISSUE THREAD

**Issue by diatomsRcool** [EcologicalSemantics/ecocore#55]
I did some research on primary nutritional modes and it turns out that things are much more complicated that autotroph vs heterotroph, of course. I decided to adjust the definition of autotroph and heterotroph so that they are differentiated by using inorganic or organic carbon for biomass. The subclasses of autotroph and heterotroph are defined by using either light, inorganics, or organics for energy. I'm open to discussing this. Thoughts? @pbuttigieg

**Comment by diatomsRcool** [comment]
![image](https://user-images.githubusercontent.com/5140552/45902391-4b4e8480-bdb4-11e8-80f8-9749cc6f3a1d.png)

**Comment by diatomsRcool** [comment]
Energysource | Oxidizingdonorsource | Carbon source | Name | Examples
-- | -- | -- | -- | --
Sun LightPhoto- | Organic-organo- | Organic-heterotroph | Photoorganoheterotroph | Some bacteria (Rhodobacter)
Carbon dioxide-autotroph | Photoorganoautotroph |  
Inorganic-litho-* | Organic-heterotroph | Photolithoheterotroph |  
Carbon dioxide-autotroph | Photolithoautotroph | Some bacteria (blue green algae), some eukaryotes (eukaryotic algae, land plants). Photosynthesis.
BreakingChemicalCompoundsChemo- | Organic-organo- | Organic-heterotroph | Chemoorganoheterotroph | Some eukaryotes (heterotrophic protists, fungi, animals)
Carbon dioxide-autotroph | Chemoorganoautotroph | Some archaea (anaerobic methanotrophic archaea).[8] Chemosynthesis.
Inorganic-litho-* | Organic-heterotroph | Chemolithoheterotroph | Some bacteria (Oceanithermus profundus)[9]
Carbon dioxide-autotroph | Chemolithoautotroph | Some bacteria (Nitrobacter), some archaea (Methanobacteria). Chemosynthesis.

**Comment by diatomsRcool** [comment]
All from here https://en.wikipedia.org/wiki/Primary_nutritional_groups

**Comment by pbuttigieg** [comment]
> I did some research on primary nutritional modes and it turns out that things are much more complicated that autotroph vs heterotroph, of course.

Of course :grin: 

>  I decided to adjust the definition of autotroph and heterotroph so that they are differentiated by using inorganic or organic carbon for biomass.

Hmm: "inorganic" and "organic" carbon can mean quite different things to different domains. The safest bet is to be explicit and say that a heterotroph uses biogenic C-bearing compounds as its carbon source while an autotroph uses abiogenic C-bearing compounds. We can axiomatise biogenic C-bearing compounds by saying something like:
* biogenic organic compound =def. CHEBI:[`organic molecular entity`](http://purl.obolibrary.org/obo/CHEBI_50860) and _output_of_ some GO:[`biological process`](http://purl.obolibrary.org/obo/GO_0008150)
* abiogenic organic compound =def. =def. CHEBI:[`organic molecular entity`](http://purl.obolibrary.org/obo/CHEBI_50860) **not** _output_of_ some GO:[`biological process`](http://purl.obolibrary.org/obo/GO_0008150)

You'll notice that CHEBI's "organic" just means C-bearing. 


>  The subclasses of autotroph and heterotroph are defined by using either light, inorganics, or organics for energy. 

Sounds good, the 3 dimensions (energy source, C-source, oxidant source) you list in the table are quite well-used to classify trophic modes. It may be complicated, but it's the most resilient and coherent classification I've seen.

**Comment by pbuttigieg** [comment]
This system risks multiple inheritance, but can be managed. 
The various nutritional modes should have equivalence axioms like those demonstrated above which can be used to reason any classes/instances into multiple locations as needed. This way, we can keep the asserted hierarchy relatively flat and avoid asserted multiple inheritance.

**Comment by diatomsRcool** [comment]
photoorganoheterotroph
photoorganoautotroph
photolithoheterotroph
photolithoautotroph
chemoorganoheterotroph
chemoorganoautotroph
chemolithoheterotroph
chemolithoautotroph

**Comment by diatomsRcool** [comment]
In v2019-03-15
