### ISSUE TITLE
new term: Epigeic

### ISSUE THREAD

**Issue by richardostler** [EcologicalSemantics/ecocore#57]
## Preferred term label
epigeic

## Synonyms
surface dweller

## Textual definition
Organisms living on the surface of the soil and in leaf litter.

## Suggested parent term
http://purl.obolibrary.org/obo/PATO_0001995

## Attribution
https://orcid.org/0000-0002-1434-9495

**Comment by richardostler** [comment]
Adjective, so agree with your suggestions, thanks!

**Comment by diatomsRcool** [comment]
In v2019-03-15
