### ISSUE TITLE
new term: endogeic

### ISSUE THREAD

**Issue by richardostler** [EcologicalSemantics/ecocore#58]
I believe this term is specific to Earthworms, so I hope it is ok to request here. 

## Preferred term label
endogeic

## Synonyms
topsoil dwellers, endogeal

## Textual definition
Earthworms typically living in the top 20cm depth of soil and making temporary horizontal burrows

## Suggested parent term
http://purl.obolibrary.org/obo/PATO_0001995

## Attribution
https://orcid.org/0000-0002-1434-9495

**Comment by diatomsRcool** [comment]
For clarity, are you wanting to describe endogeic the adjective or endogeic organism the noun?

If the adjective, how about this definition instead:
"An organismal quality inhering in a bearer by virtue of the bearer's ability to live in the top 20 cm of soil"

And for the synonym: top soil dwelling, endogeal

Can we make the definition inclusive to earthworms but not excluding everything else?

**Comment by richardostler** [comment]
I think it can be an adjective, but in the case of earthworms, endogeic also includes the burrowing behaviour of the animal - it is perhaps more important than the actual soil zone the animal lives as deeper burrowing worms will traverse this zone but have different burrowing behaviours.

I think it can be more inclusive, but I don't think there are many other taxa occupying similar niches.

**Comment by diatomsRcool** [comment]
OK, let's try this:
"An organismal quality inhering in a bearer by virtue of the bearer's ability to live in the top 20 cm of soil and make temporary, horizontal burrows."

**Comment by richardostler** [comment]
I think that definition works, thanks for the help

**Comment by diatomsRcool** [comment]
In v2019-03-15
