### ISSUE TITLE
new term: anecic

### ISSUE THREAD

**Issue by richardostler** [EcologicalSemantics/ecocore#59]
I believe this term is specific to Earthworms, so I hope it is ok to request here. 

## Preferred term label
anecic

## Synonyms
subsoil dweller, deep burrowing

## Textual definition
Deep burrowing earthworms making permanent vertical burrows

## Suggested parent term
http://purl.obolibrary.org/obo/PATO_0001995

## Attribution
https://orcid.org/0000-0002-1434-9495

**Comment by diatomsRcool** [comment]
For clarity, are you wanting to describe anecic the adjective or anecic organism the noun?

If the adjective, how about this definition instead:
"An organismal quality inhering in a bearer by virtue of the bearer's ability to burrow more than 20 cm soil depth"

And for the synonym: subsoil dwelling, deep burrowing

Can we make the definition general enough to include earthworms but not exclude others?

**Comment by richardostler** [comment]
Similar comment to epigeic, I think it can be an adjective, but in the case of earthworms, this includes the burrowing behaviour of the animal

I think it can be more inclusive, but again I don't think there are many other taxa occupying similar niches or exhibiting similar behaviour.

**Comment by diatomsRcool** [comment]
Let's try this:
"An organismal quality inhering in a bearer by virtue of the bearer's ability to burrow more than 20 cm deep into the soil and make permanent, vertical burrows"

**Comment by richardostler** [comment]
I think that definition works, thanks for the help

**Comment by diatomsRcool** [comment]
In v2019-03-15
