### ISSUE TITLE
nutritional modes: processes

### ISSUE THREAD

**Issue by diatomsRcool** [EcologicalSemantics/ecocore#60]
I'm going to propose that we define the processes that go along with the nutritional modes as granularly as possible.
autotrophy
heterotrophy
phototrophy
lithotrophy
organotrophy
lithotrophy

Then something like photoorganoautotroph will be tagged as capable of autotrophy, organotrophy, and phototrophy.

**Comment by diatomsRcool** [comment]
phototrophy: obtaining energy from light
chemotrophy: obtaining energy from preformed molecules
lithotrophy: use inorganic compound as electron donor
organotrophy: use organic compound as electron donor

**Comment by diatomsRcool** [comment]
Either we have autotrophy, heterotrophy, phototrophy, chemotrophy, lithotrophy, and organotrophy as sister classes under trophic interaction and use combinations of them in the axiomatic definitions of the nutritional mode classes, such as chemolithoheterotroph is capable of some chemotrophy and lithotrophy and heterotrophy
OR
We made a process for each type of nutritional mode, such as chemolithoheterotroph is capable of some chemolithoheterotrophy
@pbuttigieg opinion?

**Comment by cmungall** [comment]
My slight preference is to only have process classes, and to introduce a synonym scope to have the 'thing' name attached directly to the process. But if there is a use case for continuants then make shadow classes (but be sure to have a yaml template)

**Comment by cmungall** [comment]
(the name change OSK->ODK was independent of the switch to yaml)

There is no turnkey solution, but with a bit of understanding of the workings it should not be so hard to migrate. I suggest experimenting setting up a fake new ecocore repo using a yaml config. From there it will hopefully be more obvious how to copy things across, we can set up a PR for this

**Comment by diatomsRcool** [comment]
I've been working with Nico to update ecocore to ODK.
