### ISSUE TITLE
NTR: leaf miner

### ISSUE THREAD

**Issue by diatomsRcool** [EcologicalSemantics/ecocore#63]
For new term requests, please provide the following information:

## Preferred term label

leaf miner

## Textual definition

an herbivore that lives in and eats the leaf tissue of plants

## Suggested parent term

herbivore

## Attribution

http://orcid.org/0000-0002-2908-3327

* Need to include the "living in the leaf" part in the logic

**Comment by diatomsRcool** [comment]
Add synonym or narrow synonym https://www.wikidata.org/entity/Q1544843

**Comment by diatomsRcool** [comment]
@jhammock
Any objection to making this a child of folivore?

**Comment by jhammock** [comment]
That sounds good to me, unless any of them make tunnels in leaves without
consuming them. I have not heard of such a leaf miner.

**Comment by diatomsRcool** [comment]
a leaf miner class has been added, but I cannot update the relationship to "living in the leaf" without an additional relation from RO. I added it to the import file, but won't be able to axiomatize until after the next release.

**Comment by diatomsRcool** [comment]
#119
