### ISSUE TITLE
NTR: herbivorous grazer

### ISSUE THREAD

**Issue by diatomsRcool** [EcologicalSemantics/ecocore#64]
For new term requests, please provide the following information:

## Preferred term label

herbivorous grazer

## Textual definition

an herbivore that primarily consumes grasses, leaves, and other soft plant material.

## Suggested parent term

herbivore

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by diatomsRcool** [comment]
add as broad synonym https://www.wikidata.org/wiki/Q37619060

**Comment by diatomsRcool** [comment]
The issue here is that "grazer" is used to refer to herbivores like cows and to omnivores like oysters or microzooplankton. "Grazing" is also used to refer to fish that eat epiphytes and small animals off of coral reefs or rocks. This term is meant to refer only to herbivores like cows. The WikiData definition includes reference to "algae", which suggests that term is also meant to be used in reference to oysters and ciliates. However, oysters and ciliates are, while not totally indiscriminate, do not restrict themselves solely to algae. I think we should have another class to describe the oysters and ciliates of the world.

**Comment by diatomsRcool** [comment]
Does that mean EOL would prefer one term called "grazing" that is defined as "feeding by slowly lumbering through an environment and eating off of a surface" or something like that? That would be separate from what they are eating? Because the EOL definition of grazer includes "grasses, forbs, or algae" - and includes "herbivore".

**Comment by jhammock** [comment]
Yeah, we haven't got much data in yet in these categories, and the grazer data dates from before we worked it out- and it happens to be all herbivorous grazer records. So far you can see the "feeding methods" intent only in filter feeder (which we have currently from wikidata). It's a child of consumer right now.

**Comment by diatomsRcool** [comment]
What I propose is that we keep herbivorous grazer and add "grazing" that is strictly a process that describes that feeding method. Then add "capable of some grazing" and "capable of some herbivory" as axiomatic definitions of herbivorous grazer. EOL just has to decide if its going to tag taxa with the entity grazer or the process grazing. How does that sound?

**Comment by diatomsRcool** [comment]
@jhammock If you send me your ORCID, I'll will add you as a term editor

**Comment by diatomsRcool** [comment]
@jhammock would it be ok for me to make herbivorous grazer a child of folivore?

**Comment by jhammock** [comment]
Yeah, I can't think of other plant parts grazers feed on. Flower, wood and
root feeders all have other feeding habit descriptors, I think. Stems? No,
I think grazing on plants is always leaves

**Comment by jhammock** [comment]
https://orcid.org/0000-0002-9943-2342

**Comment by diatomsRcool** [comment]
Need to add "grass" class

**Comment by jhammock** [comment]
they don't always. They eat plants...

**Comment by diatomsRcool** [comment]
Right, I have several equivalence axioms, but I think I should just delete them all.

**Comment by diatomsRcool** [comment]
OK, this one is fixed.

**Comment by diatomsRcool** [comment]
#119
