### ISSUE TITLE
NTR: herbivorous browser

### ISSUE THREAD

**Issue by diatomsRcool** [EcologicalSemantics/ecocore#65]
For new term requests, please provide the following information:

## Preferred term label

herbivorous browser

## Textual definition

An herbivore that primarily consumes twigs, leaves, and bark of trees and shrubs.

## Suggested parent term

herbivore

## Attribution

http://orcid.org/0000-0002-2908-3327

**Comment by diatomsRcool** [comment]
The EOL definitions of grazer and browser emphasize the height of the plant being eaten, with grazers eating low to the ground and browsers eating higher up. I'm not sure this is a robust distinction.

**Comment by diatomsRcool** [comment]
@jhammock any opinion? Can we change the TraitBank definition?

**Comment by jhammock** [comment]
I haven't seen strong evidence either way, but we may recode browsers to grazers in due course. I think making a new term now is probably premature.
