### ISSUE TITLE
parent of trophic interaction

### ISSUE THREAD

**Issue by diatomsRcool** [EcologicalSemantics/ecocore#70]
Should trophic interaction (ecocore_00000008) be a subclass of multi-organism process (GO_0051704) rather than process (BFO_0000015)?

**Comment by diatomsRcool** [comment]
@jhpoelen @cmungall @pbuttigieg 
Any opinions?

**Comment by jhpoelen** [comment]
According to RO, a trophic interaction is a biotic-biotic interaction. RO's biotic-biotic interaction http://purl.obolibrary.org/obo/RO_0002574 is defined as a ```participates in a biotic-biotic interaction with```. Please also note that a biotic-biotic interaction is a kind of a biotic interaction. RO's biotic interaction can be a ```An interaction relationship in which at least one of the partners is an organism and the other is either an organism or an abiotic entity with which the organism interacts.``` 

So, to me, the statement trophic interaction is a multi-organism process seems consistent with RO's view on the world. Also, the statement is more specific than saying that a trophic interaction is a process.

I am assuming that cross references are being made with RO terms to show that there's multiple wheels being invented. Which lead to the question: is there a re-inventing-of-the-wheel ontology yet?

**Comment by diatomsRcool** [comment]
Right, there's multiple ways to do things, which isn't inherently bad. Especially when the data record is spotty. For example, maybe a taxon is a reported fungivore, which is a trophic interaction and the type of thing one might see in TraitBank. For another organism we have a documented incidence of an organism eating a fungus, which is the type of thing that would use an RO term and be found in GloBI. We need to make sure these two different ways of representing data are compatible. I'll think about this.

Something occurred to me though. Right now, I have processes like autotrophy as a subclass of trophic interaction. Autotrophy, is a trophic process, but does not involve more than one organism. Maybe the best thing to do is rather than trophic interaction, have trophic process. Is there value in having a class to contain all the different ways organisms obtain food and nutrition?

**Comment by cmungall** [comment]
OWL enforces a strict subdivision between properties and classes (well you may be able to get around it via punning but not recommended).

So we have parallels between shortcut `x R y` and `r type R, x participates-in r, y participates-in R`. We've tried different ways of formalizing this in RO, originally the SELF pattern but have settled on SWRL rules. We have these established for things like phopshorylates vs GO kinase activity. See https://www.slideshare.net/cmungall/causal-reasoning-using-the-relation-ontology?qid=a57249c4-e593-4ead-9fef-45ede43ffa69&v=&b=&from_search=2

I think RO should be used to bootstrap ecocore classes and check coverage, but the relations should be defined in terms of classes

**Comment by cmungall** [comment]
> Should trophic interaction (ecocore_00000008) be a subclass of multi-organism process (GO_0051704) rather than process (BFO_0000015)?

only if all TIs are evolved biological programs. If X has evolved to eat Y (or at least things of Y's general class), yes. So me eating a pig, yes. But me accidentally swallowing a fly, no.

**Comment by jhpoelen** [comment]
@diatomsRcool I agree that having many wheels is not necessarily a bad thing. My comments about the many wheels ontology is more of a question of how to best keep track of the various related terms / concepts / definitions. 

As far as the "trait"-like fungivore property vs a specific observation of some individual organism eating some individual fungus - I feel comfortable taking a view that report of a fungivore property for a specific taxon is rooted in some observation of an individual eating some fungus without any information about location event time. So, when GloBI encounters ```X is a frugivore```, the information is a captured in a statement ```some X ate some fungus according to ...```. This is how GloBI can handle both general claims like humans are fungivores and more specific claims like this individual human organisms was observed eating that fungus at domino's pizza last week. This does not cover nuances of the "X has evolved to eat Y" vs "X ate Y" scenario.

**Comment by diatomsRcool** [comment]
considering the discussion above I propose to change "trophic interaction" to "trophic process" and make it a child of "biological process". Any opinions?

**Comment by cmungall** [comment]
Hate to complicate things but we might want to coordinate this with GO. in
GO BP is only the evolved process. This gets interesting when we think of
multi-organism processes. There is of course co-evolution. But I think the
correct way to think of the GO BP is from the side of one organism.

**Comment by diatomsRcool** [comment]
@cmungall what is the best way to coordinate with GO?

**Comment by cmungall** [comment]
Let's just start with a linked ticket in go-ontology. Ask if 'trophic
interaction' is in scope of GO, and if it's not in scope to be in GO itself
(e.g. it may be too broad encompassing a lion eating a wildebeest and a
bacterium 'feeding') is it a valid subclass managed in another ontology.

**Comment by diatomsRcool** [comment]
looks like trophic interaction is not considered in scope for GO. It is now a child of biological process and considering some trophic processes are not interactions between multiple organisms. I am going to leave it where it is in the hierarchy and change the name to trophic process.
