### ISSUE TITLE
NTR: microcarnivore

### ISSUE THREAD

**Issue by diatomsRcool** [EcologicalSemantics/ecocore#82]
For new term requests, please provide the following information:

## Preferred term label

microcarnivore

## Textual definition

A predator that primarily eats small invertebrates, such as microcrustaceans, small molluscs, and bryozoan larvae

## Suggested parent term

predator or insectivore

## Attribution

http://orcid.org/0000-0002-2908-3327

**Comment by diatomsRcool** [comment]
@Jen Hammock
Is this meant to refer solely to marine microcarnivores? What is the relationship to insectivores? Are insectivores a type of microcarnivore?

**Comment by diatomsRcool** [comment]
@jhammock any thoughts?

**Comment by jhammock** [comment]
I wish I'd given you the reference for the definition above- I can't find it now. But I don't feel the need to stick with something so specific. Looking at it now, I'd prefer something like "A carnivore that primarily eats small animals" with an indication of size threshold. The literature doesn't seem inclined to provide one, though they love this term. Perhaps we go out on a limb? Up to 1mm in maximum dimension?

**Comment by jhammock** [comment]
I wish I'd given you the reference for the definition above- but I don't feel the need to stick with something so specific. Looking at it now, I'd prefer something like "A carnivore that primarily eats small animals" with an indication of size threshold. The literature doesn't seem inclined to provide one, though they love this term. Perhaps we go out on a limb? Up to 1mm in maximum dimension?

**Comment by diatomsRcool** [comment]
If we use the 1mm maximum we are excluding some insectivores, but not all. What if we say small invertebrates and don't give a size threshold? Would a carnivore that eats those tiny frogs be considered a microcarnivore?

**Comment by jhammock** [comment]
I always thought that micro was meant in the usual measurement sense. I'm
fine with leaving out some insectivores; they have their own label. I
wouldn't limit it to invertebrates either. I don't know about tiny frogs,
but fish eggs on the menu have qualified marine microcarnivores in some
papers.

**Comment by diatomsRcool** [comment]
How about the following definition "A predator that primarily eats prey less than 1 cm in its longest dimension"

and its a child of predator

**Comment by jhammock** [comment]
I'm good with 1cm, but I'm pretty sure predation is not implied by microcarnivore (i.e.; they could scavenge dead animals), so I'd still prefer carnivore, and making it a child of carnivore.

**Comment by diatomsRcool** [comment]
and are those dead animals also small?

**Comment by jhammock** [comment]
Yes

**Comment by diatomsRcool** [comment]
#119
