### ISSUE TITLE
lichenicole vs lichenicolous

### ISSUE THREAD

**Issue by diatomsRcool** [EcologicalSemantics/ecocore#86]
@jhammock
Can I get some background on the choice of lichenicole over lichenicolous? Or how it is being currently used? I've pasted some text from an amateur web site below that discusses the term more through the lens of substrate rather than trophic association.
Whatever we do for lichenicole we should do for lignicolous, saxicolous, etc. (see below). I'm not sure we should have lignicole, saxicole, etc., but maybe its not a problem.
Do we want to bake in the parasitic association or make it just about the substrate?

The consequence of lichenicole vs lichenicolous is one of entity vs quality. Do we want to tag organisms as be lichenicoles or as having the quality lichenicolous? Does it matter to EOL? I would rather have lichenicolous, I think. Thoughts?

"The term substrate gets used in two senses. In the first place, it can refer to the substance that the fungus uses as food. The mycelium of the fungus grows through this kind of substrate, secreting enzymes that dissolve part of the substrate, and absorbing the nutrition that results. This "growing through" leads us to the second sense, which is "whatever sort of substance the fruiting body (or other visible token of the fungus) appears on." Usually, these two senses refer to the same substance, but not always.

The other terms discussed in this entry tell you what kind of substrate you have. A lignicolous fungus has wood as its substrate. A fungicolous fungus grows on other fungi. A lichenicolous or lichenicole lichen grows on other lichens. A saxicolous lichen grows on rocks. Fungi whose fruiting bodies come up from the ground are usually called terrestrial, although you may also see any of the terms beginning with terr-. Snell actually gives the term terraneous a slightly different meaning, that of growing on dry land (as opposed, presumably, to growing underwater or in some sort of swampy situation)."

**Comment by jhammock** [comment]
we made the choice arbitrarily, I think, but we use entity rather than quality for all trophic assignments in EOL. Probably because available entity forms outnumbered quality forms when we started. It behooves us to try to be consistent for natural language generation, etc. We can always pile on synonym relationships as needed

**Comment by diatomsRcool** [comment]
OK. So you treat the relationship as Taxon is a <X>. That's fine, although I will point out that some of the trophic terms are written as adjectives or verbs rather than nouns, such as hematophagy and heterotrophic, etc. At least that's how it is in the diagram katja shared.

**Comment by jhammock** [comment]
Yeah, like most of our terms policy, there are inconsistent cases from
before we started forming habits.

**Comment by diatomsRcool** [comment]
Final decision is to use lichenicole
