### ISSUE TITLE
Add behaviour semantics: Import from NBO?

### ISSUE THREAD

**Issue by pbuttigieg** [EcologicalSemantics/ecocore#9]
The [Neuro Behavior Ontology](http://www.obofoundry.org/ontology/nbo.html) has many classes of great relevance to general ethology, despite its focus on humans. We should add this to our import stack and announce ECOCORE to that space. 

We've heard (unconfirmed) reports that the semantics from other ontologies in this space (SIBO, SPD) are being merged into NBO. Will have to confirm this. 

In the meantime, we'll pull in NBO as see where we get.

xref: https://github.com/obo-behavior/behavior-ontology/issues/43

**Comment by diatomsRcool** [comment]
There is an animal behavior ontology 
https://github.com/obo-behavior/behavior-ontology/tree/master/animal-behavior-ontology
