### ISSUE TITLE
definition of active foraging

### ISSUE THREAD

**Issue by diatomsRcool** [EcologicalSemantics/ecocore#93]
@jhammock
Is the intent for active foraging to include hunting? Does a lion engage in active foraging? The difference could be that one involves pursuit (hunting) while the other doesn't?

**Comment by jhammock** [comment]
I think we use it for omnivores, by which logic it could be a parent of hunting

**Comment by diatomsRcool** [comment]
Not necessarily. If a user searched for active foragers, would you want them to get lion in their results?

**Comment by diatomsRcool** [comment]
Looking at what's in TraitBank, it appears that the answer would be no, active foraging should not include hunting. This term is more for food items that just sit there whether they be plant or animal.
