### ISSUE TITLE
Map trophy types to IMG

### ISSUE THREAD

**Issue by cmungall** [EcologicalSemantics/ecocore#98]
See for example:

https://img.jgi.doe.gov/cgi-bin/w/main.cgi?section=TaxonDetail&page=taxonDetail&taxon_oid=2513020023

I don't know if we want to precompose all kinds of https://en.wikipedia.org/wiki/Auxotrophy I don't see why not

**Comment by diatomsRcool** [comment]
Cool. Is there a comprehensive list of the trophic types that JGI is interested in?

**Comment by diatomsRcool** [comment]
- [ ] auxotroph

- [ ] prototroph

**Comment by diatomsRcool** [comment]
#119
